openapi: 3.0.0
servers:
  - url: 'https://restcountries.com'
info:
  description: 'REST countries API'
  title: REST countries API
  version: v2.0.5
paths:
  /v2/all:
    get:
      operationId: v2All
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/alpha/{alphacode}:
    get:
      operationId: v2Alphacode
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: alphacode
          description: Search by ISO 3166-1 2-letter or 3-letter country code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/alpha:
    get:
      operationId: v2Alphacodes
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: codes
          description: Search by list of ISO 3166-1 2-letter or 3-letter country codes
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/currency/{currency}:
    get:
      operationId: v2Currency
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: currency
          description: Search by ISO 4217 currency code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/name/{name}:
    get:
      operationId: v2Name
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: name
          description: Search by country name. It can be the native name or partial name
          in: path
          required: true
          schema:
            type: string
        - name: fullText
          in: query
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/callingcode/{callingcode}:
    get:
      operationId: v2Callingcode
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: callingcode
          description: Search by calling code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/capital/{capital}:
    get:
      operationId: v2Capital
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: capital
          description: Search by capital city
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/continent/{region}:
    get:
      operationId: v2Region
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: region
          description: "In version 2 regions are continent and subregions are region Search by continent: Africa, Americas, Asia, Europe, Oceania"
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/lang/{lang}:
    get:
      operationId: v2Lang
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: lang
          description: Search by ISO 639-1 language code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/regionalbloc/{regionalbloc}:
    get:
      operationId: v2Regionalbloc
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: regionalbloc
          description: >
            Search by regional bloc:
              EU (European Union)
              EFTA (European Free Trade Association)
              CARICOM (Caribbean Community)
              PA (Pacific Alliance)
              AU (African Union)
              USAN (Union of South American Nations)
              EEU (Eurasian Economic Union)
              AL (Arab League)
              ASEAN (Association of Southeast Asian Nations)
              CAIS (Central American Integration System)
              CEFTA (Central European Free Trade Agreement)
              NAFTA (North American Free Trade Agreement)
              SAARC (South Asian Association for Regional Cooperation)
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v3/all:
    get:
      operationId: v3All
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v3/alpha/{alphacode}:
    get:
      operationId: v3Alphacode
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: alphacode
          description: Search by ISO 3166-1 2-letter or 3-letter country code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v3/alpha:
    get:
      operationId: v3Alphacodes
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: codes
          description: Search by list of ISO 3166-1 2-letter or 3-letter country codes
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v3/currency/{currency}:
    get:
      operationId: v3Currency
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: currency
          description: Search by currency code or name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v3/name/{name}:
    get:
      operationId: v3Name
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: name
          description: Search by country name. It can be the common or official value
          in: path
          required: true
          schema:
            type: string
        - name: fullText
          in: query
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v3/capital/{capital}:
    get:
      operationId: v3Capital
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: capital
          description: Search by capital city
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v3/region/{region}:
    get:
      operationId: v3Region
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: region
          description: In version 3, continents are Regions and regions are Subregions
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v3/subregion/{subregion}:
    get:
      operationId: v3Subregion
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: subregion
          description: You can search by subregions
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v3/lang/{lang}:
    get:
      operationId: v3Lang
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: lang
          description: Search by language code or name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v3/demonym/{demonym}:
    get:
      operationId: v3Demonym
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: demonym
          description: Now you can search by how a citizen is called.
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v3/translation/{translation}:
    get:
      operationId: v3Translation
      parameters:
        - name: fields
          description: You can filter the output of your request to include only the specified fields.
          in: query
          required: false
          schema:
            type: string
        - name: translation
          description: You can search by any translation name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
components:
  schemas: { }